### ISSUE TITLE
Add `.cast` feature

### ISSUE THREAD

**Issue by dcrockwell** [FreeAllMedia/stimpak#28]
Allow a function to be provided which modifies each provided answer

``` javascript
stimpak.cast(answer => parseInt(answer));
```

**Comment by dcrockwell** [comment]
Should support multiple `.cast` calls:

``` javascript
stimpak.cast(answer => parseInt(answer));
stimpak.cast(answer => parseSomeOtherThing(answer));
```

**Comment by warang580** [comment]
Note: it applies to answers after the cast() calls, not previous ones.

**Comment by warang580** [comment]
I have started something but I have a problem. When I do this :

``` javascript
stimpak
    .prompt(promptUntouched)
    .cast(callbackA)
    .cast(callbackB)
    .prompt(promptCasted);
```

And try to display the casts that have been added like this

``` javascript
inquirer
    .prompt(unansweredPrompt)
    .then(questionAnswers => {
        console.log("questionAnswers", questionAnswers);
        console.log("casts", this.cast());
        this.answers(questionAnswers);
        done();
    });
```

I get this :

```
? Answer 5 please ! 5
questionAnswers { untouched: '5' }
casts [ [Function: callbackA], [Function: callbackB] ]
? Answer 5 please ! 5
questionAnswers { casted: '5' }
casts [ [Function: callbackA], [Function: callbackB] ]
```

Meaning that I get all callbacks I register via cast(), even for the first prompt which is meant to be untouched. It is because we are listing all prompts that should be used, and not using them instantly.

You can get all the code here : https://github.com/warang580/stimpak/tree/feat/cast

Maybe I should set the cast on each prompt ? It would be more meaningful, because I don't see lots of usecase where you use the same cast for a bunch of prompts like it is done now. It would look like this : 

``` javascript
let promptCasted = {
    type: "input",
    name: "casted",
    message: "Answer 5 please !",
    cast: answer => parseInt(answer) + 2,
    default: "5",
};
```

**Comment by dcrockwell** [comment]
The issue is that `.then(thenFunction)` takes a function that has two optional parameters: `stimpak`, and an optional `done` callback in case you need the function to be asynchronous.

So, you'll need to refactor your then statement to this:

``` javascript
stimpak
    .then(() => {
        const questionAnswers = stimpak.answers();
        console.log("questionAnswers", questionAnswers);
        console.log("casts", stimpak.cast());
        this.answers(questionAnswers);
    });
```

**Comment by dcrockwell** [comment]
Alternately, you can also do it this way, which illustrates the optional arguments:

``` javascript
stimpak
    .then(doSomething);

function doSomething(stimpak) {
    const questionAnswers = stimpak.answers();
    console.log("questionAnswers", questionAnswers);
    console.log("casts", stimpak.cast());
    this.answers(questionAnswers);
}
```

**Comment by dcrockwell** [comment]
Make sure that within casting you're adding it as a step in the _.action.steps chain. Let me know if you'd also like to discuss this over Discord, etc.
